### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by emailsubjekt** [abehaskins/firepit#11]
Hi, when I use the exe file and run it for the first time it gives out the following error below:

###############

~ Let's make sure your Firebase CLI is ready...
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ChildProcess.checkSpawn.on (C:\snapshot\firepit\welcome.js:82:27)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:595:12)

###########

Any advice how to fix this error?

**Comment by alamari** [comment]
I am facing the same error exactly. Did you manage to fix it ?

**Comment by Yke222** [comment]
I Managed to fix this by just typing "firebase" in the console within the exe file, you guys should try that.

**Comment by Yke222** [comment]
It'll them download all necessary files to run

**Comment by acuvic** [comment]
> I Managed to fix this by just typing "firebase" in the console within the exe file, you guys should try that.

Yes, this works for me, thanks! I typed "firebase" in the console that popped-up while installing via exe

**Comment by Tahira6020** [comment]
1. delete **C:\Users\USERNAME\.cache\firebase**
2. Run firebase-win-exe
3. Authentication process will start you press Y
    Allow Firebase to collect CLI and Emulator Suite usage and error reporting information? Y
4. Copy a google link and paste it into browser and Log into your google account to allow access to firebase
5.  Success! Logged in as tahira6020@gmail.com

<img width="952" alt="Screenshot 2024-03-30 232741" src="https://github.com/abeisgoat/firepit/assets/57070186/76b399bf-3ea7-4ddc-ac5a-4ef3168f3e91">
