### ISSUE TITLE
Errors trying to use "firebase" and "npm" commands

### ISSUE THREAD

**Issue by jsayol** [abehaskins/firepit#2]
```
D:\Downloads\Firepit>systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134
```

I just gave it a try but there seems to be something wrong. For the record, I don't have Node.js installed on my Windows machine although from what I understand it shouldn't be necessary, right?

Here's what I'm seeing:
``` 
Welcome to the Firebase Shell! You can type 'firebase' or 'npm' to run commands!

D:\Downloads\Firepit>npm
internal/modules/cjs/loader.js:594
    throw err;
    ^

Error: Cannot find module 'is:npm'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:592:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1280:46)
    at Function.Module._load (internal/modules/cjs/loader.js:518:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)

D:\Downloads\Firepit>firebase
> help
ReferenceError: help is not defined
> ?
?
^

SyntaxError: Unexpected token ?

> exit
ReferenceError: exit is not defined
> quit
ReferenceError: quit is not defined
>
(To exit, press ^C again or type .exit)
>

D:\Downloads\Firepit>firebase --help
internal/modules/cjs/loader.js:594
    throw err;
    ^

Error: Cannot find module '--help'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:592:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1280:46)
    at Function.Module._load (internal/modules/cjs/loader.js:518:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)

D:\Downloads\Firepit>firebase init
internal/modules/cjs/loader.js:594
    throw err;
    ^

Error: Cannot find module 'init'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:592:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1280:46)
    at Function.Module._load (internal/modules/cjs/loader.js:518:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```

I tried enabling debug logging with --pit:log-debug but it just logs an extra "Welcome to firepit!" line at the beginning

**Comment by abeisgoat** [comment]
I notice your downloads folder is on your `D:\` drive, could you try running the .exe from your `C:\` and seeing if this still happens?

**Comment by jsayol** [comment]
Same result:

```
C:\Users\josep\Firepit>firepit-win.exe --pit:log-debug
Welcome to firepit!
Welcome to the Firebase Shell! You can type 'firebase' or 'npm' to run commands!

C:\Users\josep\Firepit>npm
internal/modules/cjs/loader.js:594
    throw err;
    ^

Error: Cannot find module 'is:npm'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:592:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1280:46)
    at Function.Module._load (internal/modules/cjs/loader.js:518:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)

C:\Users\josep\Firepit>firebase --help
internal/modules/cjs/loader.js:594
    throw err;
    ^

Error: Cannot find module '--help'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:592:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1280:46)
    at Function.Module._load (internal/modules/cjs/loader.js:518:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```

**Comment by jsayol** [comment]
I tried installing node but that doesn't seem to make a difference either:

```
C:\Users\josep\Firepit>node --version
v10.15.0

C:\Users\josep\Firepit>npm --version
6.4.1

C:\Users\josep\Firepit>firepit-win.exe --pit:log-debug
Welcome to firepit!
Welcome to the Firebase Shell! You can type 'firebase' or 'npm' to run commands!

C:\Users\josep\Firepit>firebase --version
internal/modules/cjs/loader.js:594
    throw err;
    ^

Error: Cannot find module '--version'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:592:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1280:46)
    at Function.Module._load (internal/modules/cjs/loader.js:518:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```

**Comment by abeisgoat** [comment]
You should definitely *not* need node or npm. This package contains versions of both and ignores system-level installs. I have a general idea of what's happening here, just not sure why. I'll do some digging and follow up. Thanks again for testing!

**Comment by abeisgoat** [comment]
Alright, I've brewed up a [new build](http://storage.googleapis.com/fir-tools-builds/firepit/firepit-win.exe) which at the very least show allow better debugging with `--pit:log-debug`. If you can, give it a shot by just clicking the .exe and if it's still broken, send the debug output!

**Comment by jsayol** [comment]
Sorry, same result with a bit extra debug output at start time:

```
C:\Users\josep\Firepit>firepit-win.exe --pit:log-debug
Welcome to firepit!
C:\Users\josep\Firepit\FIREPI~1.EXE
Node path C:\Users\josep\Firepit\FIREPI~1.EXE is runtime? false
Welcome to the Firebase Shell! You can type 'firebase' or 'npm' to run commands!

C:\Users\josep\Firepit>firebase --version
module.js:547
    throw err;
    ^

Error: Cannot find module '--version'
    at Function.Module._resolveFilename (module.js:545:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1280:46)
    at Function.Module._load (module.js:472:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (bootstrap_node.js:227:16)
    at bootstrap_node.js:648:3

C:\Users\josep\Firepit>npm --version
module.js:547
    throw err;
    ^

Error: Cannot find module 'is:npm'
    at Function.Module._resolveFilename (module.js:545:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1280:46)
    at Function.Module._load (module.js:472:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (bootstrap_node.js:227:16)
    at bootstrap_node.js:648:3
```

**Comment by abeisgoat** [comment]
That's okay! We're getting there. Thanks for being so responsive.

Once you're in the shell, can you try running the same .exe again? (so instead of `firebase --version` try `firepit-win.exe --version`)

**Comment by jsayol** [comment]
Same error:

```
C:\Users\josep\Firepit>firepit-win.exe --pit:log-debug
Welcome to firepit!
C:\Users\josep\Firepit\FIREPI~1.EXE
Node path C:\Users\josep\Firepit\FIREPI~1.EXE is runtime? false
Welcome to the Firebase Shell! You can type 'firebase' or 'npm' to run commands!

C:\Users\josep\Firepit>firepit-win.exe --version
module.js:547
    throw err;
    ^

Error: Cannot find module '--version'
    at Function.Module._resolveFilename (module.js:545:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1280:46)
    at Function.Module._load (module.js:472:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (bootstrap_node.js:227:16)
    at bootstrap_node.js:648:3
```

**Comment by abeisgoat** [comment]
Okie dokie, lets [try again](http://storage.googleapis.com/fir-tools-builds/firepit/firepit-win.exe). With any luck we should see `Node path C:\Users\josep\Firepit\FIREPI~1.EXE is runtime? true` - I believe that's the route issue :)

**Comment by jsayol** [comment]
😕
```
C:\Users\josep\Firepit>firepit-win.exe --pit:log-debug
Welcome to firepit!
Node path C:\Users\josep\Firepit\FIREPI~1.EXE is runtime? false
C:\Users\josep\Firepit\FIREPI~1.EXE
Welcome to the Firebase Shell! You can type 'firebase' or 'npm' to run commands!
```

**Comment by abeisgoat** [comment]
We're gonna get this soon. Added more debug in [this build](http://storage.googleapis.com/fir-tools-builds/firepit/firepit-win-0-0-3.exe).

**Comment by jsayol** [comment]
Hey, at least there's something new. There seems to be an error on start-up:

```
C:\Users\josep\Firepit>firepit-win.exe --pit:log-debug
Welcome to firepit v0.0.3!
STDERR: module.js:547
    throw err;

STDERR:  ^

Error: Cannot find module '--eval'
    at Function.Module._resolveFilename (module.js:545:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1280:46)
    at Function.Module._load (module.js:472:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (bootstrap_node.js:227:16)
    at bootstrap_node.js:648:3

[VerifyNodePath] Expected "✓" from runtime got code 1 with output ""
Node path C:\Users\josep\Firepit\FIREPI~1.EXE is runtime? false
C:\Users\josep\Firepit\FIREPI~1.EXE
Welcome to the Firebase Shell! You can type 'firebase' or 'npm' to run commands!
```

Off-topic, but the `✓` character doesn't render well on the terminal:
![capture](https://user-images.githubusercontent.com/2029586/51709899-ef2c9300-2027-11e9-9902-d0c68de273c2.PNG)

**Comment by jsayol** [comment]
In case it helps, if I run `firepit.js` directly then things seem to work OK:

```
C:\Users\josep\Firepit\firepit>node firepit.js
Welcome to firepit v0.0.3!
C:\PROGRA~1\nodejs\node.exe
STDOUT: ✓

[VerifyNodePath] Expected "✓" from runtime got code 0 with output "✓
"
Node path C:\PROGRA~1\nodejs\node.exe is runtime? true
C:\PROGRA~1\nodejs\node.exe C:\Users\josep\Firepit\firepit\firepit.js
Welcome to the Firebase Shell! You can type 'firebase' or 'npm' to run commands!

C:\Users\josep\Firepit\firepit>firebase
Please wait while the Firebase CLI downloads...
C:\Users\josep\.cache\firebase\cli\firebase -> C:\Users\josep\.cache\firebase\cli\node_modules\firebase-tools\lib\bin\firebase.js
C:\Users\josep\.cache\firebase\cli\npm -> C:\Users\josep\.cache\firebase\cli\node_modules\npm\bin\npm-cli.js
C:\Users\josep\.cache\firebase\cli\npx -> C:\Users\josep\.cache\firebase\cli\node_modules\npm\bin\npx-cli.js
npm WARN lifecycle The node binary used for scripts is C:\Program Files\nodejs\node.exe but npm is using C:\PROGRA~1\nodejs\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @google-cloud/functions-emulator@1.0.0-beta.5 postinstall C:\Users\josep\.cache\firebase\cli\node_modules\firebase-tools\node_modules\@google-cloud\functions-emulator
> node scripts/upgrade-warning


If you're using the Emulator via the Firebase CLI, you can
disregard this message.

If you're upgrading @google-cloud/functions-emulator, these
are the recommended upgrade steps:

1.  Stop the currently running emulator, if any:

        functions stop

2.  Uninstall the current emulator, if any:

        npm uninstall -g @google-cloud/functions-emulator

3.  Install the new version of the emulator:

        npm install -g @google-cloud/functions-emulator

If you have trouble after upgrading, try deleting the config
directory found in:

    ~/.config/configstore/@google-cloud/functions-emulator

Then restart the emulator. You can also check for any renegade
Node.js emulator processes that may need to be killed:

    ps aux | grep node

+ firebase-tools@6.3.0
+ npm@6.7.0
added 970 packages from 938 contributors in 116.047s

C:\Users\josep\Firepit\firepit>firebase
Usage: firebase [options] [command]

Options:
  -V, --version                              output the version number
  -P, --project <alias_or_project_id>        the Firebase project to use for this command
  -j, --json                                 output JSON instead of text, also triggers non-interactive mode
  --token <token>                            supply an auth token for this command
  --non-interactive                          error out of the command instead of waiting for prompts
  --interactive                              force interactive shell treatment even when not detected
  --debug                                    print verbose debug output and keep a debug log file
  -h, --help                                 output usage information

Commands:
  auth:import [options] [dataFile]           import users into your Firebase project from a data file(.csv or .json)
  auth:export [options] [dataFile]           Export accounts from your Firebase project into a data file
  database:get [options] <path>              fetch and print JSON data at the specified path
  database:push [options] <path> [infile]    add a new JSON object to a list of data in your Firebase
  database:set [options] <path> [infile]     store JSON data at the specified path via STDIN, arg, or file
  database:remove [options] <path>           remove data from your Firebase at the specified path
  database:update [options] <path> [infile]  update some of the keys for the defined path in your Firebase
  database:profile [options]                 profile the Realtime Database and generate a usage report
  firestore:delete [options] [path]          Delete data from Cloud Firestore.
  firestore:indexes [options]                List indexes in your project's Cloud Firestore database.
  deploy [options]                           deploy code and assets to your Firebase project
  hosting:disable [options]                  stop serving web traffic to your Firebase Hosting site
  functions:log [options]                    read logs from deployed functions
  functions:shell [options]                  launch full Node shell with emulated functions
  functions:config:clone [options]           clone environment config from another project
  functions:config:get [path]                fetch environment config stored at the given path
  functions:config:set [values...]           set environment config with key=value syntax
  functions:config:unset [keys...]           unset environment config at the specified path(s)
  functions:delete [options] [filters...]    delete one or more Cloud Functions by name or group name.
  experimental:functions:shell [options]     launch full Node shell with emulated functions. (Alias for `firebase functions:shell.)
  help [command]                             display help information
  init [feature]                             setup a Firebase project in the current directory
  list                                       list the Firebase projects you have access to
  login [options]                            log the CLI into Firebase
  login:ci [options]                         generate an access token for use in non-interactive environments
  logout                                     log the CLI out of Firebase
  open [link]                                quickly open a browser to relevant project resources
  serve [options]                            start a local server for your static assets
  setup:web                                  display this project's setup information for the Firebase JS SDK
  setup:emulators:database                   downloads the database emulator
  setup:emulators:firestore                  downloads the firestore emulator
  target [type]                              display configured deploy targets for the current project
  target:apply <type> <name> <resources...>  apply a deploy target to a resource
  target:clear <type> <target>               clear all resources from a named resource target
  target:remove <type> <resource>            remove a resource target
  tools:migrate [options]                    ensure your firebase.json format is up to date
  use [options] [alias_or_project_id]        set an active Firebase project for your working directory

C:\Users\josep\Firepit\firepit>firebase --version
6.3.0
```

**Comment by abeisgoat** [comment]
That does help :) That means as soon as we get this issue sorted, then it'll fall into place haha. Just uploaded [0.0.4](http://storage.googleapis.com/fir-tools-builds/firepit/firepit-win-0-0-4.exe) which will hopefully be the magic one.

**Comment by jsayol** [comment]
👍 🎉 🎆 

I made sure to delete `~/.cache/firebase` for a clean slate before running this.

Just as a note, the first time running `firebase` installs it but doesn't actually run it. Also it might be a good idea to hide the npm-install output, might be a bit confusing.

Otherwise, looks great!

```
C:\Users\josep\Firepit>firepit-win.exe --pit:log-debug
Welcome to firepit v0.0.4!
STDOUT: ✓

[VerifyNodePath] Expected "✓" from runtime got code 0 with output "✓
"
Node path C:\Users\josep\Firepit\FIREPI~1.EXE is runtime? true
C:\Users\josep\Firepit\FIREPI~1.EXE C:\snapshot\firepit\firepit.js
Welcome to the Firebase Shell! You can type 'firebase' or 'npm' to run commands!

C:\Users\josep\Firepit>firebase --version
Please wait while the Firebase CLI downloads...
C:\Users\josep\.cache\firebase\cli\firebase -> C:\Users\josep\.cache\firebase\cli\node_modules\firebase-tools\lib\bin\firebase.js
C:\Users\josep\.cache\firebase\cli\npm -> C:\Users\josep\.cache\firebase\cli\node_modules\npm\bin\npm-cli.js
C:\Users\josep\.cache\firebase\cli\npx -> C:\Users\josep\.cache\firebase\cli\node_modules\npm\bin\npx-cli.js

> @google-cloud/functions-emulator@1.0.0-beta.5 postinstall C:\Users\josep\.cache\firebase\cli\node_modules\firebase-tools\node_modules\@google-cloud\functions-emulator
> node scripts/upgrade-warning


If you're using the Emulator via the Firebase CLI, you can
disregard this message.

If you're upgrading @google-cloud/functions-emulator, these
are the recommended upgrade steps:

1.  Stop the currently running emulator, if any:

        functions stop

2.  Uninstall the current emulator, if any:

        npm uninstall -g @google-cloud/functions-emulator

3.  Install the new version of the emulator:

        npm install -g @google-cloud/functions-emulator

If you have trouble after upgrading, try deleting the config
directory found in:

    ~/.config/configstore/@google-cloud/functions-emulator

Then restart the emulator. You can also check for any renegade
Node.js emulator processes that may need to be killed:

    ps aux | grep node

+ firebase-tools@6.3.0
+ npm@6.7.0
added 970 packages from 938 contributors in 99.071s

C:\Users\josep\Firepit>firebase --version
6.3.0

C:\Users\josep\Firepit>npm --version
6.7.0
```

**Comment by abeisgoat** [comment]
Yooo we did it team. Thanks so much for your help and the bit about installing but not invoking is great feedback. I've been thinking about doing the install automatically on first run, but that's a discussion for another bug.

Anywho, good stuff. Hopefully no one else ever has an issue ever again.
